//DELETE http://localhost:3002/api/persons/6
GET http://localhost:3002/api/persons

###
POST http://localhost:3002/api/persons 
content-type: application/json

{
    "name" : "Sami Sarkasti",
    "number": "030-333 0939"
}

###

POST http://localhost:3002/api/persons 
content-type: application/json

{
    "name" : "Sirkku Sarkasti",
    "number": "030-333 0939"
}

###

POST http://localhost:3002/api/persons 
content-type: application/json

{
    "name" : "aöshj"
}

###


POST http://localhost:3002/api/persons 
content-type: application/json

{
    "name" : "",
    "number": "2097643"
}

###

POST http://localhost:3002/api/persons 
content-type: application/json

